add_newline = true
format = "$username$hostname$directory$git_branch$git_status$nix_shell\n$character"

[character]
disabled = false
error_symbol = "[󱞪](red)"
success_symbol = "[󱞪](green)"

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
read_only = "  "
read_only_style = "red"
style = "blue"
truncation_length = 4
truncation_symbol = "…/"

[git_branch]
format = "on [$symbol$branch]($style) "
style = "bold red"
symbol = " "

[git_status]
ahead = "[ ($count) ](green)"
behind = "[ ($count) ](yellow)"
conflicted = "[ ($count) ](red)"
deleted = "[ ($count) ](red)"
format = "[$all_status]()"
modified = "[ ($count) ](yellow)"
renamed = "[ ($count) ](purple)"
staged = "[ ($count) ](cyan)"
stashed = "[ ($count) ](blue)"
untracked = "[ ($count) ](blue)"

[hostname]
disabled = false
format = "in [$ssh_symbol$hostname ](bold blue)"
ssh_only = true
ssh_symbol = " "

[line_break]
disabled = false

[nix_shell]
disabled = false
format = "[on  Nix Shell](blue)"

[username]
disabled = false
format = "[ $user]($style) "
show_always = true
style_root = "red bold"
style_user = "green bold"
